language: php

php:
  - 8.0

sudo: false

services:
  - sqlite3

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - php artisan key:generate
  - php artisan test
